---
# application tasks to be customized and to run after the main provision
- name: Compile environment virtual host
  template:
    src: "stepic.conf.j2"
    dest: "/home/box/web/etc/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
  register: app_ini

- name: Enable environment virtual host
  file:
    path="/etc/nginx/sites-enabled/stepic.conf"
    src="/home/box/web/etc/nginx.conf"
    state=link
    owner=root group=root
  when: app_ini|changed
  become: yes
  notify: restart nginx

- name: Install Gunicorn server
  pip: name=gunicorn