---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml

  roles:
    - swap
    - server
    - vagrant_local
    - jdauphant.ssl-certs
    - geerlingguy.nginx
    - geerlingguy.mysql
    - geerlingguy.memcached
    - app
